apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fedprox

# id-distributor: 30021
# ds-distributor: 17500
# server port: 30051
# worker port: 30051
# log-collector: 24224

resources:
  - namespace.yaml
  - logserver.yaml
  - ds_partitioner.yaml
  - miscs.yaml
  - server.yaml
  - worker.yaml
# replacements:
#   - source:

